version: '3'

services:
  app:
    image: node:lts
    container_name: micchanfs
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"
    ports:
    - "127.0.0.1:3000:3000"
    - "127.0.0.1:12321:12321"